name: Generate

on:
  workflow_dispatch:
    inputs:
      repo_name:
        type: string
        description: "The name of the repository to create"
        required: true
      template:
        type: choice
        description: "The framework template you'd like to use"
        required: true
        options:
          - NextJS
          - Serverless

jobs:
  generate:
    name: Generate Repository
    runs-on: fool-runners
    steps:
      - name: Get Target Template Repo
        id: target_template
        run: |
          if [[ ${{ inputs.template }} == "NextJS" ]]; then
            echo "repo=themotleyfool/tmf-nextjs-template-poc" >> $GITHUB_OUTPUT
          else
            echo "repo=themotleyfool/tmf-serverless-template" >> $GITHUB_OUTPUT
          fi

      - name: Checkout Template Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.target_template.outputs.repo }}
          path: code
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Substitute Variables
        run: |
          cd $GITHUB_WORKSPACE/code
          LC_CTYPE=C && LANG=C && find . -type f -exec sed -i -e 's/{{ TMF_TEMPLATE_REPO_NAME }}/${{ inputs.repo_name }}/g' {} +

      - name: Create New Repository
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/themotleyfool/repos \
            -d '{"name":"${{ inputs.repo_name }}","private":true,"visibility":"private","allow_merge_commit":false,"delete_branch_on_merge":true}'

      - name: Remove Sample Dotenvx Files
        run: |
          cd $GITHUB_WORKSPACE/code
          for file in .env.*; do
            rm $file
          done

      - name: Push to new Repository
        run: |
          cd $GITHUB_WORKSPACE/code
          git config --global user.name "Github Action"
          git config --global user.email "<>"
          git add .
          git commit -m "Replace template variables with repository information and remove sample .env.* files"
          git remote add copy https://${{ secrets.GH_TOKEN }}@github.com/themotleyfool/${{ inputs.repo_name }}.git
          git push -u copy main --no-thin

      - name: Assign Repository Permissions
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/themotleyfool/${{ inputs.repo_name }}/collaborators/${{ github.actor }} \
            -d '{"permission":"admin"}'
